# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to HockeyApp"
  lane :mopub do
  	next if ENV["CI"]
    # Build
    gym(
      scheme: "PlayableMopubAd",
      workspace: "PlayableMopubAd.xcworkspace",
      configuration: "Release",
      clean: true,
      include_symbols: true,
      export_method: "enterprise"
    )

    # Push to HockeyApp
    hockey(
      api_token: "b23874100f5346cdb613ca63c57393eb",
      public_identifier: '369fdb7db11d4fa6997b1d24203d5a7f',
      notify: "1",
      status: "2",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: ENV["TRAVIS_COMMIT_MESSAGE"],
      timeout: 300
    )
  end
end
